name: Run R Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-r-script:
    runs-on: windows-latest
    # retrieve secrets from github
    env:
        apikey: ${{ secrets.APIKEY}}
        apisecretkey: ${{ secrets.APISECRETKEY}}
        access_token: ${{ secrets.ACCESS_TOKEN}}
        access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        RENV_PATHS_ROOT: ~/.local/share/renv

 steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: renv

      - uses: r-lib/actions/setup-renv@v2

      - name: Cache packages
        uses: actions/cache@v1
        with:
           path: ${{ env.RENV_PATHS_ROOT }}
           key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
           restore-keys: |-
              ${{ runner.os }}-renv-

    - name: Run R script
      run: |
        Rscript R/00-access-newdata-thermo-git.R  # Replace with the actual filename of your script, e.g., 'script.R'
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}  # You can store your GitHub token here for authentication

    - name: Commit and push data (optional)
      if: success()  # This step will only run if the script succeeds
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"
        git add .
        git commit -m "Update data from latest script run"
        git push
