name: Run R Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        R -e 'install.packages(c("httr", "purrr", "dplyr", "tidyr", "tibble", "readr", "stringr"))'

    - name: Run R script
      run: Rscript R/00-access-newdata-thermo-git.R
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Results from R script" || echo "No changes to commit"
        git push origin || echo "No changes to commit"
