# This is a basic workflow that only runs on schedule

name: run_job_scripts_Meteo_QualidadeDoAr

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  run-r-script:
    runs-on: ubuntu-latest  # Faster than Windows

    env:
        apikey: ${{ secrets.APIKEY}}
        apisecretkey: ${{ secrets.APISECRETKEY}}
        access_token: ${{ secrets.ACCESS_TOKEN}}
        access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}
        GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        PLUG_API: ${{ secrets.PLUG_API }}
        PLUG_AUTH: ${{ secrets.PLUG_AUTH }}
        PURPLEAIR_API: ${{ secrets.PURPLEAIR_API }}
        INMET_TOKEN: ${{ secrets.INMET_TOKEN }}
        RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Check if cache restored
        run: ls -lah ${{ env.RENV_PATHS_ROOT }} || echo "Cache not restored"

      - name: Ensure renv is installed
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        shell: Rscript {0}

      - name: Restore R packages
        run: renv::restore()
        shell: Rscript {0}

      # execute Rscript
      - name: Execute Script
        run: |
          source("R/00-access-plugfield-data.R")
        shell: Rscript {0}

      - name: Execute Script
        run: |
          source("R/00-access-purpleair-data.R")
        shell: Rscript {0}

      - name: Execute Script
        run: |
          source("R/00-access-INMET_API-data.R")
        shell: Rscript {0}

      - name: Execute Script
        run: |
          source("R/01-meteo_hour.R")
        shell: Rscript {0}

      - name: Execute Script
        run: |
          source("R/00-access-REPOnewdata-thermo-git.R")
        shell: Rscript {0}

      - name: Execute Script
        run: |
          source("R/00-data_wrangling_thermo.R")
        shell: Rscript {0}

      - name: Execute Script
        run: |
          source("R/01-AQI_calculation_thermo_data.R")
        shell: Rscript {0}

      # --- Auto-commit and push changes to data files ---
      - name: Commit and push any changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/*.Rda data/meteo/*.Rda data_raw/*.Rda || echo "No changes to add"
          git commit -m "Auto-commit updated data files [skip ci]" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
