name: Telegram Alert

on:
  push:
      branches: [ "main" ]
  schedule:
    - cron:   "0 */6 * * *"  # Runs every 6h
  workflow_dispatch:

jobs:
  send_telegram:
        runs-on: windows-latest
    # retrieve secrets from github
        env:
            apikey: ${{ secrets.APIKEY}}
            apisecretkey: ${{ secrets.APISECRETKEY}}
            access_token: ${{ secrets.ACCESS_TOKEN}}
            access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}
            GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
            RENV_PATHS_ROOT: ~/.local/share/renv

        steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v4

          - uses: r-lib/actions/setup-r@v2
            with:
              use-public-rspm: true
              r-version: renv

          - uses: r-lib/actions/setup-renv@v2

          - name: Cache packages
            uses: actions/cache@v4
            with:
               path: ${{ env.RENV_PATHS_ROOT }}
               key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
               restore-keys: |-
                  ${{ runner.os }}-renv-
               #  fail-on-cache-miss: true

          - name: Send Telegram Alert
            env:
               TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
               TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
            run: Rscript R/01-alert_telegram.R
